language: python

python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "3.8"

install:
  - pip install --upgrade -r testing-requirements.txt
  - pip install -e .

script:
  - pytest --cov . --ignore tests/test_live_client.py

after_success:
  - codecov
